### ISSUE TITLE
Problems with nokogiri

### ISSUE THREAD

**Issue by Ricardo1980** [valeriomazzeo/danger-the_coding_love#2]
Hello,
I have several problems related to nokogiri plugin.
Can you tell more or less how to rewrite your plugin to avoid using nokogiri?
Thanks in advance.

**Comment by valeriomazzeo** [comment]
Hey,

Nokogiri is used to parse the html of the coding love website.
I suppose you are having troubles similar to this:
https://stackoverflow.com/questions/23668684/nokogiri-failed-to-build-gem-native-extension-when-i-run-bundle-install

make sure you use rvm and bundler, it will work just fine.

**Comment by Ricardo1980** [comment]
Thanks! I will try that. Meanwhile, is there any other way to parse a HTML? Maybe a lightweight parser plugin or similar?...
Thanks.

**Comment by valeriomazzeo** [comment]
there are many ruby libraries, I suppose nokogiri is the most famous
