### ISSUE TITLE
A lot of missing links

### ISSUE THREAD

**Issue by ollitapa** [valeriomazzeo/danger-the_coding_love#5]
Hi, I've started to get a lot of empty links posted from coding love. Seems that the site has wrapped all the gifs to a <video> tag, so the current parsing of <img> tag won't find them. I'll add a PR for a fix.

<img width="704" alt="screenshot 2019-01-29 at 8 54 01" src="https://user-images.githubusercontent.com/4511526/51890057-cb5caa80-23a3-11e9-814a-54106a100c9c.png">

**Comment by valeriomazzeo** [comment]
Fixed by #6
